channels:
- bioconda
- conda-forge
- defaults
dependencies:
- openjdk=11
- jupyter-server-proxy
- websockify
- pip
- pip:
   - py2neo==2021.0.1
   - gspread
   - oauth2client
   - pygithub
   - tqdm
   - pandas
